; $Id: Const.Inc,v 1.2 2004/07/27 04:01:38 Павел Exp $
;

OS_WIN32s             Equ 1000    ; Microsoft Win32s

OS_WINDOWS_95         Equ 6000    ; Microsoft Windows 95
OS_WINDOWS_95_OSR2    Equ 6001    ; Microsoft Windows 95 OSR2
OS_WINDOWS_98         Equ 7000    ; Microsoft Windows 98
OS_WINDOWS_98_SE      Equ 7001    ; Microsoft Windows 98 Second Edition

OS_WINDOWS_ME         Equ 8000    ; Microsoft Windows Millenium Edition

OS_WINDOWS_NT         Equ 5000    ; Microsoft Windows NT
OS_WINDOWS_SERVER_ENT Equ 5002    ; Microsoft Windows NT Server Enterprise Edition
OS_WINDOWS_SERVER_STD Equ 5003    ; Microsoft Windows NT Server

OS_WINDOWS_2000       Equ 4000    ; Microsoft Windows 2000
OS_WINDOWS_2000_HOME  Equ 4002    ; Microsoft Windows 2000 Home Edition
OS_WINDOWS_2000_PROF  Equ 4003    ; Microsoft Windows 2000 Professional
OS_WINDOWS_2000_DATA  Equ 4004    ; Microsoft Windows 2000 Datacenter Server
OS_WINDOWS_2000_ADV   Equ 4005    ; Microsoft Windows 2000 Advanced Server
OS_WINDOWS_2000_SERV  Equ 4006    ; Microsoft Windows 2000 Server


OS_WINDOWS_2003       Equ 2000    ; Microsoft Windows Server 2003
OS_WINDOWS_2003_DATA  Equ 2001    ; Microsoft Windows Server 2003 Datacenter Edition
OS_WINDOWS_2003_ENT   Equ 2001    ; Microsoft Windows Server 2003 Advanced Server
OS_WINDOWS_2003_WEB   Equ 2002    ; Microsoft Windows Server 2003 Web Server
OS_WINDOWS_2003_STD   Equ 2003    ; Microsoft Windows Server 2003 Standard Edition

OS_WINDOWS_XP         Equ 3000    ; Microsoft Windows XP
OS_WINDOWS_XP_HOME    Equ 3002    ; Microsoft Windows XP Home Edition
OS_WINDOWS_XP_PROF    Equ 3003    ; Microsoft Windows XP Professional
